name: "Google Cloud Container Registry"
description: "Push a docker image to Google Cloud Container Registry"

branding:
  icon: "upload-cloud"
  color: "red"

inputs:
  username:
    description: "Registry username"
    required: false
    default: "_json_key"
  creds:
    description: "Registry password"
    required: true
  registry:
    description: "Registry host name (must match image)"
    required: false
    default: "gcr.io"
  image:
    description: "Image name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Push to Google Cloud Container Registry
      shell: bash
      run: |
        docker login --username '${{ inputs.username }}' --password '${{ inputs.creds }}' 'https://${{ inputs.registry }}' 2>/dev/null
        docker push '${{ inputs.image }}' --all-tags
        echo "Successfully pushed ${{ inputs.image }}"
